CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID NUMBER,
    EMP_FIRSTNAME VARCHAR2(20),
    EMP_LASTNAME VARCHAR2(20),
    DEPARTMENT_ID NUMBER,
    SALARY NUMBER,
    EMP_EMAIL VARCHAR2(100),
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY
        (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);

CREATE TABLE DEPARTMENT(
    DEPARTMENT_ID NUMBER,
    DEPARTMENT_NAME VARCHAR(40),
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPARTMENT_ID)
);

CREATE SEQUENCE EMP_ID_GEN START WITH 1;
CREATE SEQUENCE DEPARTMENT_ID_GEN START WITH 1;

CREATE OR REPLACE TRIGGER ADD_EMP
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT EMP_ID_GEN.NEXTVAL
    INTO :NEW.EMPLOYEE_ID
    FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER ADD_DEPARTMENT
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN
    SELECT DEPARTMENT_ID_GEN.NEXTVAL
    INTO :NEW.DEPARTMENT_ID
    FROM DUAL;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_EMPLOYEE
(FNAME IN VARCHAR2, LNAME IN VARCHAR2, DPT_ID IN NUMBER, 
    SALARY IN NUMBER, EMAIL IN VARCHAR2)
AS
BEGIN
    INSERT INTO EMPLOYEE VALUES(-1, FNAME, LNAME, 
        DPT_ID, SALARY, EMAIL);
COMMIT;
END;
/

--INSERT DPTMNTS FIRST, SINCE THEY ARE FK IN EMP
INSERT INTO DEPARTMENT VALUES (-1, 'Magisterium');
INSERT INTO DEPARTMENT VALUES (-1, 'Cajoling');
INSERT INTO DEPARTMENT VALUES (-1, 'Legal');

INSERT INTO EMPLOYEE VALUES (-1, 'Jimmy','Corncracker', 2, 30000, 'dontcare@ark.gov');
INSERT INTO EMPLOYEE VALUES (-1, 'John','Barleycorn', 2, 50000, 'plowedsownharrowed@midsummer.org');
INSERT INTO EMPLOYEE VALUES (-1, 'Tom','O''Bedlam ', 1, 130000, 'earthytoes@zappos.com');
INSERT INTO EMPLOYEE VALUES (-1, 'Cave','Johnson', 2, 45000, 'c.j@aperture.org');
INSERT INTO EMPLOYEE VALUES (-1, 'John','Riley', 3, 74000, 'notforcars@gugle.com');
INSERT INTO EMPLOYEE VALUES (-1, 'Michael','Cornshucker', 1, 33000, 'children@korn.edu');

SELECT DEPARTMENT.DEPARTMENT_NAME, AVG(EMPLOYEE.SALARY)
AS AVERAGE_SAL
FROM DEPARTMENT INNER JOIN EMPLOYEE 
    ON DEPARTMENT.DEPARTMENT_ID = EMPLOYEE.DEPARTMENT_ID
GROUP BY DEPARTMENT.DEPARTMENT_NAME;